### ISSUE TITLE
How about rewriting @?

### ISSUE THREAD

**Issue by littleggghost** [FlorianWilk/SpotMicroAI#1]
Hi, @FlorianWilk 
You did a really awesome job! I can't believe that you can model a Spot-like robot and get an nice achievement in control!
There maybe has a "problem": It would be better if this code could support python2.7 and python3 simultaneously. But the grammar "@" in `kinematics.py` seems not supported in py2.7 which just means matrix multiplication.  So, maybe replace the "@" by normal grammar is better? Or wait for my PR?

Best Regards!

**Comment by FlorianWilk** [comment]
Hi littleeggghost,

thanks a lot for the nice mail. Yes, you're right about the @-Issue. I am
using Python3 since i also use it in my Jupyter-Notebooks, but yes, i will
think about rewriting it to make it work with P2.7, too.
Did the rest work for you? This Project is still at the very beginning so
expect a lot of bugs :)

Regards,
Florian

**Comment by littleggghost** [comment]
Thanks for your reply!
I will commit a PR to make it compatible with py2.7.
